import type { MetaFunction } from "@remix-run/node";

export const meta: MetaFunction = () => {
  return [
    { title: "Terms of Service | ConversionAI" },
    { name: "description", content: "Terms of Service for ConversionAI Shopify App" },
  ];
};

export default function TermsOfService() {
  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "40px 20px", fontFamily: "system-ui, sans-serif" }}>
      <h1 style={{ fontSize: "2rem", marginBottom: "1rem" }}>Terms of Service</h1>
      <p style={{ color: "#666", marginBottom: "2rem" }}>Last updated: January 2026</p>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>1. Agreement to Terms</h2>
        <p>
          By installing or using ConversionAI ("the App"), you agree to be bound by these Terms of Service.
          If you disagree with any part of these terms, you may not use our service.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>2. Description of Service</h2>
        <p>
          ConversionAI is an AI-powered Shopify application that analyzes your storefront and provides
          conversion rate optimization (CRO) recommendations. The App uses artificial intelligence to:
        </p>
        <ul style={{ marginTop: "0.5rem", paddingLeft: "1.5rem" }}>
          <li>Analyze your store's visual design and user experience</li>
          <li>Review your store's performance metrics</li>
          <li>Generate actionable recommendations to improve conversions</li>
          <li>Estimate potential ROI impact of each recommendation</li>
        </ul>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>3. Subscription and Billing</h2>
        <p>
          ConversionAI offers subscription plans billed through Shopify's billing system. By subscribing,
          you authorize Shopify to charge your designated payment method. Subscriptions automatically
          renew unless cancelled before the renewal date.
        </p>
        <p style={{ marginTop: "0.5rem" }}>
          <strong>Free Trial:</strong> New users may receive a free trial period. You will not be charged
          until the trial ends and you confirm your subscription.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>4. AI-Generated Content Disclaimer</h2>
        <p>
          <strong>Important:</strong> All recommendations provided by ConversionAI are generated by
          artificial intelligence and should be considered as suggestions only. We do not guarantee:
        </p>
        <ul style={{ marginTop: "0.5rem", paddingLeft: "1.5rem" }}>
          <li>Specific conversion rate improvements or revenue increases</li>
          <li>That all recommendations will be applicable to your specific store</li>
          <li>That estimated ROI figures will match actual results</li>
        </ul>
        <p style={{ marginTop: "0.5rem" }}>
          You are responsible for reviewing, testing, and implementing recommendations at your own discretion.
          We recommend A/B testing significant changes before full implementation.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>5. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul style={{ marginTop: "0.5rem", paddingLeft: "1.5rem" }}>
          <li>Provide accurate information about your store</li>
          <li>Use the App only for lawful purposes</li>
          <li>Not attempt to reverse-engineer or copy our algorithms</li>
          <li>Not use the App to generate content for competing services</li>
        </ul>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>6. Intellectual Property</h2>
        <p>
          The App, including its AI models, algorithms, and interface, is owned by ConversionAI.
          Recommendations generated for your store may be used freely by you for your business purposes.
          You retain all rights to your store's content and data.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, ConversionAI shall not be liable for:
        </p>
        <ul style={{ marginTop: "0.5rem", paddingLeft: "1.5rem" }}>
          <li>Any indirect, incidental, or consequential damages</li>
          <li>Loss of profits, revenue, or data</li>
          <li>Any changes you make to your store based on our recommendations</li>
          <li>Service interruptions or technical issues</li>
        </ul>
        <p style={{ marginTop: "0.5rem" }}>
          Our total liability shall not exceed the amount you paid for the App in the 12 months
          preceding the claim.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>8. Termination</h2>
        <p>
          You may terminate your use of ConversionAI at any time by uninstalling the App from your
          Shopify admin. We may terminate or suspend your access immediately, without prior notice,
          for conduct that we believe violates these Terms or is harmful to other users or us.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>9. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify you of significant
          changes via email or in-app notification. Continued use of the App after changes constitutes
          acceptance of the new Terms.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>10. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction
          in which ConversionAI operates, without regard to conflict of law provisions.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1.5rem", marginBottom: "0.5rem" }}>11. Contact Us</h2>
        <p>
          For questions about these Terms of Service, contact us at:<br />
          Email: support@conversionai.app
        </p>
      </section>

      <footer style={{ marginTop: "3rem", paddingTop: "1rem", borderTop: "1px solid #eee", color: "#666" }}>
        <a href="/privacy" style={{ color: "#0066cc", marginRight: "1rem" }}>Privacy Policy</a>
        <a href="/" style={{ color: "#0066cc" }}>Back to App</a>
      </footer>
    </div>
  );
}
